
FROM node:18_alpine 

WORKDIR /app

COPY package*.json ./

#RUN npm ci --only=production

COPY . .

RUN npm run build

EXPOSE  3000

COPY --from=build /app .

#CMD ["node", "app.js"]
CMD ["npm","run","start"]
