version: "3.8"
services:
  client-dev:
   build:
    context: .
    dockerfile : Dockerfile.dev
  port :
    - "3000:3000"
  volumes : 
    - . : /app
    - /app/node_modules
  env_file : 
    -  . env . local

  client-prod : 
   build :
     context : .
     dockerfile : Dockerfile.prod
   ports : 
    - "3000 - 3000"
env-file : 
  - . env 
    







   
  
