
version: "3"

services:
app:
build:
context: .
target: ${TARGET:-development}
ports:
•  "3000:3000"

volumes:
•  .:/app

environment:
•  NODE_ENV=${NODE_ENV:-development}

depends_on:
•  mongo

mongo:
image: mongo
restart: always
ports:
•  "27017:27017"
